// Lista completa de bancos brasileiros atualizada
// Fonte: Banco Central do Brasil - COMPE
export const brazilianBanks = [
  { code: "001", name: "Banco do Brasil S.A." },
  { code: "003", name: "Banco da Amazônia S.A." },
  { code: "004", name: "Banco do Nordeste do Brasil S.A." },
  { code: "033", name: "Banco Santander (Brasil) S.A." },
  { code: "037", name: "Banco do Estado do Pará S.A." },
  { code: "041", name: "Banco do Estado do Rio Grande do Sul S.A." },
  { code: "047", name: "Banco do Estado de Sergipe S.A." },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "077", name: "Banco Inter S.A." },
  { code: "237", name: "Banco Bradesco S.A." },
  { code: "260", name: "Nubank (Nu Pagamentos S.A.)" },
  { code: "212", name: "Banco Original S.A." },
  { code: "290", name: "Pagseguro Internet S.A. (PagBank)" },
  { code: "323", name: "Mercado Pago" },
  { code: "336", name: "Banco C6 S.A." },
  { code: "341", name: "Itaú Unibanco S.A." },
  { code: "389", name: "Banco Mercantil do Brasil S.A." },
  { code: "422", name: "Banco Safra S.A." },
  { code: "623", name: "Banco Pan S.A." },
  { code: "633", name: "Banco Rendimento S.A." },
  { code: "655", name: "Banco Votorantim S.A." },
  { code: "707", name: "Banco Daycoval S.A." },
  { code: "745", name: "Banco Citibank S.A." },
  { code: "756", name: "Banco Cooperativo do Brasil S.A. (Bancoob)" },
  { code: "748", name: "Banco Cooperativo Sicredi S.A." },
  { code: "136", name: "Unicred Cooperativa" },
  { code: "197", name: "Stone Pagamentos S.A." },
  { code: "380", name: "PicPay Servicos S.A." },
  { code: "208", name: "Banco BTG Pactual S.A." },
  { code: "246", name: "Banco ABC Brasil S.A." },
  { code: "318", name: "Banco BMG S.A." },
  { code: "739", name: "Banco Cetelem S.A." },
  { code: "743", name: "Banco Semear S.A." },
  { code: "653", name: "Banco Indusval S.A." },
  { code: "069", name: "Banco Crefisa S.A." },
  { code: "125", name: "Plural S.A. Banco Múltiplo" },
  { code: "184", name: "Banco Itaú BBA S.A." },
].sort((a, b) => a.name.localeCompare(b.name));

export const accountTypes = [
  { value: "checking", label: "Conta Corrente" },
  { value: "savings", label: "Conta Poupança" },
  { value: "payment", label: "Conta Pagamento" },
];
