// Lista completa de bancos brasileiros atualizada
// Fonte: Banco Central do Brasil - Sistema de Transferência de Reservas (STR)
// Atualizado em: 2024
// Apenas bancos que participam da COMPE
export const brazilianBanks = [
  { code: "001", name: "Banco do Brasil S.A." },
  { code: "003", name: "Banco da Amazônia S.A." },
  { code: "004", name: "Banco do Nordeste do Brasil S.A." },
  { code: "010", name: "Credicoamo Crédito Rural Cooperativa" },
  { code: "012", name: "Banco Inbursa" },
  { code: "014", name: "State Street Brasil S.A. - Banco Comercial" },
  { code: "015", name: "UBS BB Corretora de Câmbio, Títulos e Valores Mobiliários S.A." },
  { code: "016", name: "Cooperativa de Crédito Mútuo dos Despachantes de Trânsito de Santa Catarina e Rio Grande do Sul" },
  { code: "017", name: "BNY Mellon Banco S.A." },
  { code: "018", name: "Banco Tricury S.A." },
  { code: "021", name: "Banestes S.A. Banco do Estado do Espírito Santo" },
  { code: "024", name: "Banco Bandepe S.A." },
  { code: "025", name: "Banco Alfa S.A." },
  { code: "029", name: "Banco Itaú Consignado S.A." },
  { code: "033", name: "Banco Santander (Brasil) S.A." },
  { code: "036", name: "Banco Bradesco BBI S.A." },
  { code: "037", name: "Banco do Estado do Pará S.A." },
  { code: "040", name: "Banco Cargill S.A." },
  { code: "041", name: "Banco do Estado do Rio Grande do Sul S.A." },
  { code: "047", name: "Banco do Estado de Sergipe S.A." },
  { code: "063", name: "Banco Bradescard S.A." },
  { code: "064", name: "Goldman Sachs do Brasil Banco Múltiplo S.A." },
  { code: "065", name: "Banco AndBank (Brasil) S.A." },
  { code: "066", name: "Banco Morgan Stanley S.A." },
  { code: "069", name: "Banco Crefisa S.A." },
  { code: "070", name: "BRB - Banco de Brasília S.A." },
  { code: "074", name: "Banco J. Safra S.A." },
  { code: "075", name: "Banco ABN Amro Clearing S.A." },
  { code: "076", name: "Banco KDB do Brasil S.A." },
  { code: "077", name: "Banco Inter S.A." },
  { code: "078", name: "Haitong Banco de Investimento do Brasil S.A." },
  { code: "079", name: "PicPay Bank - Banco Múltiplo S.A" },
  { code: "082", name: "Banco Topázio S.A." },
  { code: "083", name: "Banco da China Brasil S.A." },
  { code: "084", name: "Sisprime do Brasil - Cooperativa de Crédito" },
  { code: "085", name: "Cooperativa Central de Crédito - Ailos" },
  { code: "088", name: "Banco Randon S.A." },
  { code: "089", name: "Credisan Cooperativa de Crédito" },
  { code: "094", name: "Banco Finaxis" },
  { code: "095", name: "Banco Travelex S.A." },
  { code: "096", name: "Banco B3 S.A." },
  { code: "097", name: "Credisis - Central de Cooperativas de Crédito Ltda." },
  { code: "098", name: "Credialiança Cooperativa de Crédito Rural" },
  { code: "099", name: "Uniprime Central Nacional - Central Nacional de Cooperativa de Crédito" },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "107", name: "Banco Bocom BBM S.A." },
  { code: "120", name: "Banco Rodobens S.A." },
  { code: "121", name: "Banco Agibank S.A." },
  { code: "122", name: "Banco Bradesco BERJ S.A." },
  { code: "124", name: "Banco Woori Bank do Brasil S.A." },
  { code: "125", name: "Banco Genial S.A." },
  { code: "132", name: "ICBC do Brasil Banco Múltiplo S.A." },
  { code: "133", name: "Confederação Nacional das Cooperativas Centrais de Crédito e Economia Familiar e Solidária - Cresol Confederação" },
  { code: "136", name: "Cooperativa Central de Crédito Unicred do Brasil" },
  { code: "208", name: "Banco BTG Pactual S.A." },
  { code: "212", name: "Banco Original S.A." },
  { code: "213", name: "Banco Arbi S.A." },
  { code: "217", name: "Banco John Deere S.A." },
  { code: "218", name: "Banco BS2 S.A." },
  { code: "222", name: "Banco Crédit Agricole Brasil S.A." },
  { code: "224", name: "Banco Fibra S.A." },
  { code: "237", name: "Banco Bradesco S.A." },
  { code: "241", name: "Banco Clássico S.A." },
  { code: "243", name: "Banco Master S/A" },
  { code: "246", name: "Banco ABC Brasil S.A." },
  { code: "254", name: "Paraná Banco S.A." },
  { code: "260", name: "Nu Pagamentos S.A." },
  { code: "265", name: "Banco Fator S.A." },
  { code: "266", name: "Banco Cédula S.A." },
  { code: "281", name: "Cooperativa de Crédito Rural Coopavel" },
  { code: "290", name: "PagSeguro Internet Instituição de Pagamento S.A." },
  { code: "318", name: "Banco BMG S.A." },
  { code: "320", name: "Bank of China (Brasil) Banco Múltiplo S/A" },
  { code: "322", name: "Cooperativa de Crédito Rural de Abelardo Luz - Sulcredi/Crediluz" },
  { code: "323", name: "Mercado Pago Instituição de Pagamento Ltda." },
  { code: "336", name: "Banco C6 S.A." },
  { code: "341", name: "Itaú Unibanco S.A." },
  { code: "348", name: "Banco XP S.A." },
  { code: "366", name: "Banco Société Générale Brasil S.A." },
  { code: "370", name: "Banco Mizuho do Brasil S.A." },
  { code: "376", name: "Banco J.P. Morgan S.A." },
  { code: "389", name: "Banco Mercantil do Brasil S.A." },
  { code: "394", name: "Banco Bradesco Financiamentos S.A." },
  { code: "422", name: "Banco Safra S.A." },
  { code: "430", name: "Cooperativa de Crédito Rural Seara - Crediseara" },
  { code: "435", name: "Delcred Sociedade de Crédito Direto S.A." },
  { code: "456", name: "Banco MUFG Brasil S.A." },
  { code: "464", name: "Banco Sumitomo Mitsui Brasileiro S.A." },
  { code: "477", name: "Citibank N.A." },
  { code: "487", name: "Deutsche Bank S.A. - Banco Alemão" },
  { code: "505", name: "Banco UBS (Brasil) S.A." },
  { code: "511", name: "Magnum Sociedade de Crédito Direto S.A." },
  { code: "600", name: "Banco Luso Brasileiro S.A." },
  { code: "604", name: "Banco Industrial do Brasil S.A." },
  { code: "610", name: "Banco VR S.A." },
  { code: "611", name: "Banco Paulista S.A." },
  { code: "612", name: "Banco Guanabara S.A." },
  { code: "623", name: "Banco Pan S.A." },
  { code: "633", name: "Banco Rendimento S.A." },
  { code: "634", name: "Banco Triângulo S.A." },
  { code: "637", name: "Banco Sofisa S.A." },
  { code: "643", name: "Banco Pine S.A." },
  { code: "653", name: "Banco Pleno S.A." },
  { code: "654", name: "Banco Digimais S.A." },
  { code: "655", name: "Banco Votorantim S.A." },
  { code: "707", name: "Banco Daycoval S.A." },
  { code: "741", name: "Banco Ribeirão Preto S.A." },
  { code: "743", name: "Banco Semear S.A." },
  { code: "745", name: "Banco Citibank S.A." },
  { code: "747", name: "Banco Rabobank International Brasil S.A." },
  { code: "748", name: "Banco Cooperativo Sicredi S.A." },
  { code: "751", name: "Scotiabank Brasil S.A. Banco Múltiplo" },
  { code: "752", name: "Banco BNP Paribas Brasil S.A." },
  { code: "753", name: "Novo Banco Continental S.A. - Banco Múltiplo" },
  { code: "755", name: "Bank of America Merrill Lynch Banco Múltiplo S.A." },
  { code: "756", name: "Banco Cooperativo Sicoob S.A. - Banco Sicoob" },
  { code: "757", name: "Banco KEB Hana do Brasil S.A." },
].sort((a, b) => a.name.localeCompare(b.name));

export const accountTypes = [
  { value: "checking", label: "Conta Corrente" },
  { value: "savings", label: "Conta Poupança" },
  { value: "payment", label: "Conta Pagamento" },
];
