project_id = "oefkzjyqjjfzfrmovfdt"

[functions.send-admin-alert]
verify_jwt = false

[functions.check-expired-projects]
verify_jwt = false

[functions.send-withdrawal-verification]
verify_jwt = true

[functions.process-withdrawal]
verify_jwt = true

[functions.stripe-connect-onboard]
verify_jwt = true

[functions.stripe-check-account]
verify_jwt = true

[functions.stripe-create-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.stripe-request-payout]
verify_jwt = true

[functions.stripe-token-checkout]
verify_jwt = true

[functions.stripe-token-webhook]
verify_jwt = false

[functions.delete-completed-projects]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-support-rating-email]
verify_jwt = true

[functions.check-support-alerts]
verify_jwt = false

[functions.check-boleto-expiration]
verify_jwt = false

[functions.sync-mailgun]
verify_jwt = true

[functions.verify-token-payment]
verify_jwt = true

[functions.send-boleto-refund-email]
verify_jwt = false
